### ISSUE TITLE
Example of list not being displayed

### ISSUE THREAD

**Issue by nlassaux** [fern-api/fern#3003]
### Describe the bug
We are using a list as example, which is a valid JSON. But the documentation doesn't show that example.

### To reproduce

1. Generate an openapi spec with the following item (I believe the fact that it's a list is the issue. Other fields work well.

```
"street_address_alias": {
	"items": {
		"type": "string"
	},
	"type": "array",
	"description": "Other known street addresses for the property. When searching for a property\nby address, these aliases will also be matched.",
	"example": [
		"123 Main St",
		"125, Main Street"
	]
},
```

2. Generate the doc
3. The example holds the key's name instead of the example.

### Expected behavior
I'd expect to see `["123 Main St", "125, Main Street"]` in place of `street_address_alias` in there.

### Screenshots

On the left, the description was pulled. But on the right, the example wasn't.

<img width="1128" alt="Screenshot 2024-02-17 at 01 47 46" src="https://github.com/fern-api/fern/assets/1917120/fb9dce83-cb72-4320-be35-968857f2a825">

### Version
Fern Version: 0.18.0

**Comment by armandobelardo** [comment]
@nlassaux would you be able to run `fern upgrade` and regenerate your docs? This should be fixed!

**Comment by nlassaux** [comment]
<img width="1436" alt="Screenshot 2024-04-18 at 21 19 02" src="https://github.com/fern-api/fern/assets/1917120/45493094-49e8-495e-b408-a7eae6e9e5a9">

I think I'm still seeing the issue. I'm now on `0.21.0`:
> Upgrading from 0.19.31 → 0.21.0

**Comment by nlassaux** [comment]
Just tried 0.22.0, I still see the same issue

**Comment by nlassaux** [comment]
@armandobelardo Just tried 0.22.0, I still see the same issue

**Comment by dannysheridan** [comment]
@chdeskur you validate on the latest version of Fern?

**Comment by chdeskur** [comment]
Confirmed this is fixed on Fern `v0.45.1`. 

```yml
responses:
...
                  items: 
                    type: array
                    item: 
                      type: string
                    description: The fields to update
                    example: [
                      "hello", 
                      "world"
                    ]
```
![Screenshot 2024-11-30 at 5 03 39 PM](https://github.com/user-attachments/assets/376f1a0c-b367-43f1-8d76-fde93c249d7b)
